version: "3.8"

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: ts-koa-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: koa
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis 服务 (可选)
  # redis:
  #   image: redis:7-alpine
  #   container_name: ts-koa-redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-koa-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_NAME: koa
      PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nodemon.json:/app/nodemon.json

volumes:
  mysql_data:
  redis_data:
